### ISSUE TITLE
Parameters Still Not Working from Package Install, Can't Recompile from Source

### ISSUE THREAD

**Issue by ufpian** [akshaysura/Sitecron#10]
Could you recompile the package for this module?  I don't believe the latest package includes the most recent pull request merge, and so the problem still exists with the jobs not accepting parameters.

I attempted to recompile the project myself, but I'm getting an error where "Templates.Script.Fields.ScriptBody" doesn't exist in SiteCron.Jobs.Powershell.ExecuteScript, in ExecuteScript.cs on line 61:

![2018-07-18 11_15_08-sitecron - microsoft visual studio administrator](https://user-images.githubusercontent.com/10515979/42890962-268b5b70-8a7c-11e8-92e7-53e63b0e5bc5.png)

**Comment by akshaysura** [comment]
Please check the latest release. Thank you.
