### ISSUE TITLE
ServerTimeZone Sitecore setting not used

### ISSUE THREAD

**Issue by Slokker** [akshaysura/Sitecron#13]
I'm running version 3.0.9 (DB Only Provider) and had the Sitecore setting ServerTimeZone patched to 'UTC'. Jobs set to run at a specific date/time are not being executed. SiteCron is not looking at the ServerTimeZone, but my local machine's time UTC+2. Sitecore itself is running UTC. The result being that jobs are always in the past, unless I schedule them at least 2 hours away.
Would be nice to see SiteCron stick to the same date/time settings as Sitecore itself is using.

**Comment by akshaysura** [comment]
@Slokker it is one of the requirements I am working on as we speak. I will keep you posted.

**Comment by akshaysura** [comment]
@Slokker I looked into this issue. Regardless of the date time, the exact date time job will be converted to UTC. I ran some tests by manipulating the UTC for the ServerTimeZone and I noticed the jobs triggering at the right time. 

I am more than happy to take a look on your machine. Also as you basing your job not running on no execution report?
