### ISSUE TITLE
Execution Reports are not created for jobs running at a specific date/time

### ISSUE THREAD

**Issue by Slokker** [akshaysura/Sitecron#14]
I'm running 3.0.9 (DB Only Provider). Running jobs based on a Cron Expression creates items under SiteCron Execution Reports, but running jobs at a Specific Date Time do not create these report items. Any idea why not?

**Comment by akshaysura** [comment]
@Slokker let me test this out and get back to you.

**Comment by Slokker** [comment]
Thank you for the quick reply!

On 2 Jul 2019, at 22:29, Akshay Sura <notifications@github.com<mailto:notifications@github.com>> wrote:


@Slokker<https://github.com/Slokker> let me test this out and get back to you.

**Comment by akshaysura** [comment]
This issue is fixed in version 3.1.0. I was able to find and fix the issue.
