### ISSUE TITLE
Powershell module dependency?

### ISSUE THREAD

**Issue by PokeyTheCat** [akshaysura/Sitecron#17]
I've recently installed Sitecron 3.1.0 (_SiteCron FULL Sitecore Package2.zip_) in my Sitecore.NET 9.0.2 (rev. 180604) local instance. My local instance is pretty bare bones. I noticed a PowerShell folder under modules and began exploring. 

When I'm attempting to look at the items in the _Script Library_ folder I get a nice null reference exception, I'm guessing because I'm missing some templates w/ standard values. That leads me to the question: 

Does this module assume that I'd have a PowerShell module installed? If so which one should I install?

![image](https://user-images.githubusercontent.com/19496973/64364431-75568200-cfd8-11e9-8481-a84d4fe18a2a.png)

> [NullReferenceException: Object reference not set to an instance of an object.]
>    Sitecore.PathAnalyzer.Extensions.ItemExtensions.IsStandardValuesItem(Item item) +44
>    Sitecore.PathAnalyzer.Client.Pipelines.GetContentEditorWarnings.MapStatus.Process(GetContentEditorWarningsArgs args) +67
>    (Object , Object ) +8
>    Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +483
>    Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists) +235
>    Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain) +21
>    Sitecore.Shell.Applications.ContentManager.Editor.GetWarnings(Boolean hasSections) +323
>    Sitecore.Shell.Applications.ContentManager.Editor.RenderPartially(Item item, Hashtable fieldInfo, Control editorsContainer) +715
>    Sitecore.Shell.Applications.ContentManager.ContentEditorForm.UpdateEditor(Item folder, Item root, Boolean showEditor) +479
>    Sitecore.Shell.Applications.ContentManager.ContentEditorForm.Update() +549
>    Sitecore.Shell.Applications.ContentManager.ContentEditorForm.OnPreRendered(EventArgs e) +204
> 
> [TargetInvocationException: Exception has been thrown by the target of an invocation.]
>    System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
>    System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +128
>    System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +142
>    Sitecore.Reflection.ReflectionUtil.InvokeMethod(MethodInfo method, Object[] parameters, Object obj) +89
>    Sitecore.Shell.Applications.ContentManager.ContentEditorPage.OnPreRender(EventArgs e) +143
>    System.Web.UI.Control.PreRenderRecursiveInternal() +200
>    System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +7479`

**Comment by akshaysura** [comment]
Hey, please install the Powershell version applicable to your Sitecore version and try again please.

**Comment by PokeyTheCat** [comment]
Installing [Sitecore Powershell Extension (SPE)](https://marketplace.sitecore.net/en/Modules/Sitecore_PowerShell_console.aspx) resolved the issue. 

Though I'm guessing your items are merely there for convenience and there's not hard dependencies on SPE, correct?

**Comment by akshaysura** [comment]
Yes indeed.
