### ISSUE TITLE
Please specify the license applicable

### ISSUE THREAD

**Issue by leovonwyss** [akshaysura/Sitecron#2]
We would like to use Sitecore in our infrastructure, but may only do so if the license is clearly defined. Can you please add a license file?

**Comment by akshaysura** [comment]
Its set as MIT license isn't it?

https://opensource.org/licenses/MIT

https://www.nuget.org/packages/SiteCron

THanks.

**Comment by akshaysura** [comment]
I just updated the GitHub with the license file. Thank you.
