### ISSUE TITLE
Smart Publish job won't accept parameter

### ISSUE THREAD

**Issue by TylerOrtiz** [akshaysura/Sitecron#8]
I am trying to use the included "SmartPublish" job. 

All fields are below:
Type: Sitecron.Jobs.Publishing.SmartPublish, Sitecron
Cron Expression: 0 0/1 * 1/1 * ? *
Execute Exactly At a Specific Date Time: None
Parameters: Target=Web
Items: None
ArchiveAfterExecution: false
Disable: false

This should try and run this task every one minute, and it keeps logging the following:

DefaultQuartzScheduler_Worker-3 02:30:00 INFO  SitePublishJob Execute - Start
DefaultQuartzScheduler_Worker-3 02:30:00 WARN  SitePublishJob Execute - Target parameter missing
DefaultQuartzScheduler_Worker-3 02:30:00 INFO  SitePublishJob Execute - End

When it clearly is defined.

EDIT:
I've replicated the code into my own project and debugged it, the only parameter that comes through is:
zSiteCronItemID

No other parameters are being passed.

**Comment by TylerOrtiz** [comment]
I have a fix for this and submit a PR if you can let me contribute. @akshaysura 

Best,

Tyler

**Comment by akshaysura** [comment]
Tyler, submit a pull request please. Thank you.

**Comment by akshaysura** [comment]
Thank you. It will be included in the next release.
